#!/usr/bin/env python3
"""Generate user/applications.md from the records in user/applications/.

The index is a PROJECTION. It is regenerated, never hand-edited, so it cannot
drift from the records the way the old single table drifted from the server.

A malformed record FAILS the build. Skipping it would reproduce exactly the
failure this design removes: an artifact that looks complete and is not.

Usage:
    python3 scripts/build_application_index.py           # write user/applications.md
    python3 scripts/build_application_index.py --check   # exit 1 if stale, write nothing
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import application_record as ar  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SCREEN_STAGES = {'phone_screen', 'technical_interview', 'onsite', 'offer'}
RECORDS = ROOT / 'user' / 'applications'
INDEX = ROOT / 'user' / 'applications.md'

MARKER = """# Application Tracker

<!-- DO NOT EDIT. Generated by scripts/build_application_index.py from
     user/applications/*.md. Edit the record files; regenerate this. -->
"""

TABLE_HEAD = """
## All applications

| Date | Last | Company | Role | Status | Sent | Source | Record |
|------|------|---------|------|--------|------|--------|--------|
"""

# HEADER stays marker + table head as one string. migrate_applications.py's
# "refuse to parse the generated index" guard and its tests both reach for
# bai.HEADER expecting the '| Date | Company |' row to be in it; splitting them
# silently disarmed that guard. Keep this composed even though render() emits
# the two halves separately with the In-flight section between them.
HEADER = MARKER + TABLE_HEAD


def _prep_link(rec, path):
    """Where the questions for this screen live, or None.

    Exists so the user never has to scroll a conversation to find prep they already have.
    That was the actual ask on 2026-08-31 -- not enforcement, findability.
    """
    declared = str(rec.get('prep', '')).strip()
    if declared:
        dp = Path(declared).expanduser()
        full = dp if dp.is_absolute() else ROOT / dp
        return declared if full.exists() else None
    resume = str(rec.get('resume', '')).strip()
    if not resume:
        return None
    pkt = ROOT / 'user' / 'tailored' / Path(resume).parent
    for pattern in ('*call*.md', '*interview*.md', '*prep*.md'):
        hits = sorted(pkt.glob(pattern))
        if hits:
            return str(hits[0].relative_to(ROOT / 'user'))
    return None


def render_in_flight(records):
    """Everything at screen stage, with a direct link to its questions. Top of the file."""
    live = [(p, r) for p, r in records
            if str(r.get('status', '')).strip() in SCREEN_STAGES]
    if not live:
        return ''
    live.sort(key=lambda pr: (pr[1]['status'], pr[1]['company']))
    out = ['\n## In flight\n',
           '| Company | Role | Stage | Questions |',
           '|---------|------|-------|-----------|']
    for path, rec in live:
        link = _prep_link(rec, path)
        cell = f'[{Path(link).name}]({link})' if link and not link.startswith('~') \
            else (f'`{link}`' if link else '**none written**')
        out.append('| {c} | {r} | {s} | {p} |'.format(
            c=_cell(rec['company']), r=_cell(rec['role']),
            s=rec['status'], p=cell))
    return '\n'.join(out) + '\n'



def _cell(value):
    """Escape a free-text value for a markdown table cell.

    application_record.py permits and preserves '|' in free-text fields
    (role, source, company). Left unescaped, a pipe splits into an extra
    table column at render time, shifting every later column out of
    alignment -- silent corruption at the render layer even though the
    record parsed cleanly. Route every free-text cell through this.
    """
    return str(value).replace('|', '\\|')


def render(records):
    rows = []
    for path, rec in sorted(records, key=lambda pr: (pr[1]['applied'],
                                                     pr[1]['company']),
                            reverse=True):
        # 'Last' is the newest event date, so "when did this last move" is
        # answerable from the index instead of by opening a 600-line record.
        # Falls back to applied: a record with no events has not moved since.
        last = max([e['date'] for e in rec.get('events') or []]
                   + [rec['applied']])
        rows.append('| {applied} | {last} | {company} | {role} | {status} | {sent} '
                    '| {source} | [{name}](applications/{name}.md) |'.format(
                        applied=rec['applied'], last=last,
                        company=_cell(rec['company']),
                        role=_cell(rec['role']), status=rec['status'],
                        sent='yes' if rec['submitted'] else 'no',
                        source=_cell(rec.get('source', '')), name=path.stem))
    return (MARKER + render_in_flight(records) + TABLE_HEAD
            + '\n'.join(rows) + ('\n' if rows else ''))


def build(records_dir):
    """Parse every record and render the index. Raises RecordError on any bad file."""
    records = [(p, ar.load(p)) for p in sorted(Path(records_dir).glob('*.md'))]
    return render(records)


PREP_GLOBS = ('*call*.md', '*interview*.md', '*prep*.md')


def check_prep(records_dir):
    """Warn for any application at screen stage with no prep sheet in its packet.

    Standing instruction, 2026-08-31: once a screen is scheduled, the questions
    go into a markdown. Writing them into chat only means they are gone by the time the
    user needs them, and re-deriving them costs the same research twice.

    A warning, not a hard failure -- this runs on every status change and a screen booked an
    hour ago has not had time to be prepped. It exists so the gap is visible, not to block.
    """
    missing = []
    for path in sorted(Path(records_dir).glob('*.md')):
        try:
            rec = ar.load(path)
        except ar.RecordError:
            continue
        if str(rec.get('status', '')).strip() not in SCREEN_STAGES:
            continue
        declared = str(rec.get('prep', '')).strip()
        if declared:
            dp = Path(declared).expanduser()
            if not dp.is_absolute():
                dp = ROOT / dp
            if dp.exists():
                continue
            missing.append((path.stem, rec.get('status'),
                            f'prep: points at {declared}, which does not exist'))
            continue
        resume = str(rec.get('resume', '')).strip()
        if not resume:
            missing.append((path.stem, rec.get('status'), 'no resume: path, cannot locate packet'))
            continue
        pkt = ROOT / 'user' / 'tailored' / Path(resume).parent
        if not pkt.is_dir():
            missing.append((path.stem, rec.get('status'), f'packet dir missing: {pkt.name}'))
            continue
        if not any(list(pkt.glob(g)) for g in PREP_GLOBS):
            missing.append((path.stem, rec.get('status'), f'no prep sheet in {pkt.relative_to(ROOT)}'))
    return missing


def _strip_references(text):
    """Remove the forms in which naming another company is LEGITIMATE.

    A record is allowed to point at another company's file. It is not allowed to
    narrate that company. So everything that is structurally a pointer comes out
    before the search runs:

      - fenced blocks and inline code spans -- `user/applications/foo.md`
      - markdown link targets -- [text](applications/foo.md)
      - any bare whitespace-delimited token containing '/', which is a path

    What survives is prose. A company name in prose is the thing being caught.
    """
    text = re.sub(r'```.*?```', ' ', text, flags=re.S)
    text = re.sub(r'`[^`]*`', ' ', text)
    text = re.sub(r'\]\([^)]*\)', '] ', text)
    text = ' '.join(t for t in text.split() if '/' not in t)
    return text


def _company_pattern(name):
    """Word-boundary regex for a company name, tolerant of internal spacing.

    Case-SENSITIVE by design. Plenty of company names are ordinary English
    words in lowercase -- 'mercury', 'imprint', 'reddit' -- and a case-insensitive
    match would fire on prose that has nothing to do with the company.
    """
    return re.compile(r'(?<![\w-])' + r'\s+'.join(
        re.escape(p) for p in name.split()) + r'(?![\w-])')


def check_isolation(records_dir):
    """Warn when a record narrates a company other than its own.

    Standing instruction, 2026-09-10: 'why are we leaving notes about
    other companies within application briefs? Everything should be isolated but
    cross referenced.'

    The failure it catches, observed the same day: one company's record carried
    several paragraphs of pipeline reasoning about four other companies. That
    made three things worse at once. The comparison went stale the moment
    anything else moved; it was invisible from the companies it was actually
    about; and reading that one record meant loading four other companies'
    state. Cross-company reasoning belongs in user/offer-timeline.md, which is
    the file whose whole job is holding it.

    A warning, not a hard failure -- same reasoning as check_prep. This fires on
    history as well as on new writes, and a gate that fails on the existing
    corpus is a gate that gets switched off on day one.
    """
    loaded = []
    for path in sorted(Path(records_dir).glob('*.md')):
        try:
            loaded.append((path, ar.load(path)))
        except ar.RecordError:
            continue

    known = {}
    for _, rec in loaded:
        name = str(rec.get('company', '')).strip()
        if name:
            known[name] = _company_pattern(name)

    hits = []
    for path, rec in loaded:
        own = str(rec.get('company', '')).strip()
        # Names that are products before they are employers -- ClickHouse, Neon,
        # Mercury. Discussing the technology is legitimate and must not be
        # reported as bleed, or the check cries wolf and stops being read.
        allowed = {p.strip() for p in
                   str(rec.get('mentions_ok', '')).split(',') if p.strip()}
        prose = _strip_references(path.read_text())
        foreign = sorted(n for n, pat in known.items()
                         if n != own and n not in allowed and pat.search(prose))
        if foreign:
            hits.append((path.stem, own, foreign))
    return hits


ISOLATION_BASELINE = ROOT / 'user' / 'isolation-baseline.txt'


def load_isolation_baseline():
    """Record stems allowed to keep narrating another company, for now.

    Same idea as `user/provenance-grandfathered.txt`, and for the same reason: a
    gate that fails 13 files on the day it ships is a gate that gets switched
    off. These 13 predate the check (2026-09-10). **The list is meant to shrink
    to zero. Never add to it** -- fix the record instead, moving the
    cross-company reasoning to user/offer-timeline.md.

    Records are gitignored, so "what changed" cannot come from git. A baseline
    is the only way to gate new writes without gating history.
    """
    if not ISOLATION_BASELINE.exists():
        return set()
    out = set()
    for line in ISOLATION_BASELINE.read_text().splitlines():
        line = line.split('#', 1)[0].strip()
        if line:
            out.add(line)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if the index is stale; write nothing')
    ap.add_argument('--gate', action='store_true',
                    help='exit 1 if a record OUTSIDE user/isolation-baseline.txt '
                         'narrates another company')
    a = ap.parse_args()

    if not RECORDS.is_dir():
        print(f'no records directory at {RECORDS}', file=sys.stderr)
        return 1
    try:
        out = build(RECORDS)
    except ar.RecordError as e:
        print(f'REFUSING to build the index: {e}', file=sys.stderr)
        return 1

    if a.check:
        current = INDEX.read_text() if INDEX.exists() else ''
        if current != out:
            print('user/applications.md is stale; run without --check',
                  file=sys.stderr)
            return 1
        print('index is current')
        return 0

    INDEX.write_text(out)
    n = out.count('\n| 20')
    print(f'wrote {INDEX.relative_to(ROOT)} ({n} records)')

    gaps = check_prep(RECORDS)
    if gaps:
        print(f'\n{len(gaps)} application(s) at screen stage with no prep sheet '
              f'-- write one with /interview-prep:', file=sys.stderr)
        for name, status, why in gaps:
            print(f'  [{status}] {name}\n      {why}', file=sys.stderr)

    bleed = check_isolation(RECORDS)
    baseline = load_isolation_baseline()
    fresh = [b for b in bleed if b[0] not in baseline]
    known = [b for b in bleed if b[0] in baseline]

    if fresh:
        print(f'\n{len(fresh)} record(s) narrate another company. Move the '
              f'cross-company reasoning to user/offer-timeline.md and leave a '
              f'path reference:', file=sys.stderr)
        for name, own, foreign in fresh:
            print(f'  {name} (record for {own})\n      names: '
                  f'{", ".join(foreign)}', file=sys.stderr)

    if known:
        print(f'\n{len(known)} pre-existing leak(s) in '
              f'{ISOLATION_BASELINE.relative_to(ROOT)} (backlog, not new):',
              file=sys.stderr)
        for name, own, foreign in known:
            print(f'  {name}: {", ".join(foreign)}', file=sys.stderr)

    # A baselined record that is now clean must leave the list, or the list
    # silently grants permission nobody re-examined. Same failure mode as a
    # stale veto rule.
    stale = sorted(baseline - {b[0] for b in bleed})
    if stale:
        print(f'\n{len(stale)} baseline entr(ies) no longer leak. Delete them '
              f'from {ISOLATION_BASELINE.relative_to(ROOT)}:', file=sys.stderr)
        for name in stale:
            print(f'  {name}', file=sys.stderr)

    if a.gate and fresh:
        print(f'\nGATE FAILED: {len(fresh)} record(s) outside the baseline.',
              file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
