#!/usr/bin/env python3
"""Generate user/applications.md from the records in user/applications/.

The index is a PROJECTION. It is regenerated, never hand-edited, so it cannot
drift from the records the way the old single table drifted from the server.

A malformed record FAILS the build. Skipping it would reproduce exactly the
failure this design removes: an artifact that looks complete and is not.

Usage:
    python3 scripts/build_application_index.py           # write user/applications.md
    python3 scripts/build_application_index.py --check   # exit 1 if stale, write nothing
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import application_record as ar  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RECORDS = ROOT / 'user' / 'applications'
INDEX = ROOT / 'user' / 'applications.md'

HEADER = """# Application Tracker

<!-- DO NOT EDIT. Generated by scripts/build_application_index.py from
     user/applications/*.md. Edit the record files; regenerate this. -->

| Date | Company | Role | Status | Sent | Source | Record |
|------|---------|------|--------|------|--------|--------|
"""


def _cell(value):
    """Escape a free-text value for a markdown table cell.

    application_record.py permits and preserves '|' in free-text fields
    (role, source, company). Left unescaped, a pipe splits into an extra
    table column at render time, shifting every later column out of
    alignment -- silent corruption at the render layer even though the
    record parsed cleanly. Route every free-text cell through this.
    """
    return str(value).replace('|', '\\|')


def render(records):
    rows = []
    for path, rec in sorted(records, key=lambda pr: (pr[1]['applied'],
                                                     pr[1]['company']),
                            reverse=True):
        rows.append('| {applied} | {company} | {role} | {status} | {sent} '
                    '| {source} | [{name}](applications/{name}.md) |'.format(
                        applied=rec['applied'], company=_cell(rec['company']),
                        role=_cell(rec['role']), status=rec['status'],
                        sent='yes' if rec['submitted'] else 'no',
                        source=_cell(rec.get('source', '')), name=path.stem))
    return HEADER + '\n'.join(rows) + ('\n' if rows else '')


def build(records_dir):
    """Parse every record and render the index. Raises RecordError on any bad file."""
    records = [(p, ar.load(p)) for p in sorted(Path(records_dir).glob('*.md'))]
    return render(records)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if the index is stale; write nothing')
    a = ap.parse_args()

    if not RECORDS.is_dir():
        print(f'no records directory at {RECORDS}', file=sys.stderr)
        return 1
    try:
        out = build(RECORDS)
    except ar.RecordError as e:
        print(f'REFUSING to build the index: {e}', file=sys.stderr)
        return 1

    if a.check:
        current = INDEX.read_text() if INDEX.exists() else ''
        if current != out:
            print('user/applications.md is stale; run without --check',
                  file=sys.stderr)
            return 1
        print('index is current')
        return 0

    INDEX.write_text(out)
    n = out.count('\n| 20')
    print(f'wrote {INDEX.relative_to(ROOT)} ({n} records)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
