#!/usr/bin/env bash
# Wire JobHub's harness-neutral prompts into a specific coding agent.
#
#   scripts/install-harness.sh claude|codex|cursor|gemini|opencode|all
#
# prompts/commands/*.md is the source of truth. This script only creates the
# per-harness plumbing each tool expects. Re-run it after adding a command.
#
# Nothing here is required: every command is a plain Markdown prompt, so you can
# always just paste prompts/commands/job.md into a chat and it works.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/prompts/commands"
cd "$REPO_ROOT"

if [ ! -d "$SRC" ]; then
  echo "error: $SRC not found — run this from inside the JobHub repo." >&2
  exit 1
fi

commands() { find "$SRC" -maxdepth 1 -name '*.md' -exec basename {} .md \; | sort; }

# Skills and agents are Claude Code specific. Other harnesses get the commands
# only; the shared knowledge a skill carries is also reachable by reading the
# SKILL.md path the commands name.
SKILLS="$REPO_ROOT/prompts/skills"
AGENTS="$REPO_ROOT/prompts/agents"
skills() { [ -d "$SKILLS" ] || return 0; find "$SKILLS" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort; }
agents() { [ -d "$AGENTS" ] || return 0; find "$AGENTS" -maxdepth 1 -name '*.md' -exec basename {} .md \; | sort; }

# Strip YAML frontmatter (harnesses that don't parse it choke on the --- fences).
strip_frontmatter() {
  awk 'NR==1 && $0=="---" {fm=1; next} fm && $0=="---" {fm=0; next} !fm {print}' "$1"
}

# Pull `description:` out of frontmatter for harnesses that want it separately.
description_of() {
  awk -F': *' '/^description:/ {sub(/^description: */,""); print; exit}' "$1"
}

link_dir() { # link_dir <target-dir-relative-to-repo> <dest>
  local target="$1" dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "  skip  $dest already exists and is not a symlink — move it aside first"
    return
  fi
  rm -f "$dest"
  ln -s "$target" "$dest"
  echo "  link  $dest -> $target"
}

install_claude() {
  echo "claude:"
  link_dir "../prompts/commands" ".claude/commands"
  link_dir "../prompts/rules"    ".claude/rules"
  # Skills and agents are linked leaf by leaf, not as whole directories, so that
  # skills or agents from other sources can live alongside them in .claude/.
  while read -r name; do
    link_dir "../../prompts/skills/$name" ".claude/skills/$name"
  done < <(skills)
  while read -r name; do
    link_dir "../../prompts/agents/$name.md" ".claude/agents/$name.md"
  done < <(agents)
  echo "  note  CLAUDE.md points at AGENTS.md; nothing else to do"
}

install_cursor() {
  echo "cursor:"
  link_dir "../prompts/commands" ".cursor/commands"
  echo "  note  Cursor also reads AGENTS.md at the repo root"
}

# opencode resolves models from models.dev, which lists hosted providers only.
# A local Ollama box is therefore invisible to it until a provider block names
# it explicitly, so `install-harness.sh opencode` used to leave README's "free
# with a local model via Ollama" as a promise with no setup step behind it.
#
# The generated file is opencode.json at the repo root. A project config MERGES
# with ~/.config/opencode/opencode.json rather than replacing it (verified), so
# this adds the provider without disturbing globally configured MCP servers.
OPENCODE_MARKER='generated by scripts/install-harness.sh'

write_opencode_ollama() {
  local host="${OLLAMA_HOST:-http://localhost:11434}"
  host="${host%/}"

  local tags
  if ! tags="$(curl -fsS -m 5 "$host/api/tags" 2>/dev/null)"; then
    echo "  skip  no Ollama at $host — set OLLAMA_HOST and re-run to generate opencode.json"
    return
  fi

  if [ -e opencode.json ] && ! grep -q "$OPENCODE_MARKER" opencode.json 2>/dev/null; then
    echo "  skip  opencode.json exists and was not generated here — add an ollama provider by hand"
    return
  fi

  # Ollama serves every model at the server's num_ctx, NOT at the context length
  # advertised in /api/tags. Advertising the larger number lets opencode pack a
  # prompt the server then silently truncates, so the served ceiling wins.
  printf '%s' "$tags" \
    | OLLAMA_BASE="$host" \
      OLLAMA_MAX_CTX="${OLLAMA_CONTEXT_LENGTH:-32768}" \
      OLLAMA_MARKER="$OPENCODE_MARKER" \
      python3 "$REPO_ROOT/scripts/opencode_ollama_config.py" > opencode.json.tmp \
    && mv opencode.json.tmp opencode.json \
    || { rm -f opencode.json.tmp; echo "  fail  could not generate opencode.json"; return 1; }

  local n
  n="$(python3 -c 'import json,sys;print(len(json.load(open("opencode.json"))["provider"]["ollama"]["models"]))')"
  echo "  gen   opencode.json -> $n tool-capable model(s) from $host"
  echo "  note  run with: opencode --model ollama/<model>   (opencode models | grep ollama)"
}

install_opencode() {
  echo "opencode:"
  link_dir "../prompts/commands" ".opencode/command"
  write_opencode_ollama
  echo "  note  opencode also reads AGENTS.md at the repo root"
}

install_codex() {
  # Codex reads prompts from ~/.codex/prompts (global, not per-repo), so these are
  # copies rather than links into the repo. Re-run after editing a command.
  echo "codex:"
  local dest="${CODEX_HOME:-$HOME/.codex}/prompts"
  mkdir -p "$dest"
  local n=0
  while read -r name; do
    strip_frontmatter "$SRC/$name.md" > "$dest/$name.md"
    n=$((n + 1))
  done < <(commands)
  echo "  copy  $n prompt(s) -> $dest"
  echo "  note  Codex prompts are global. Re-run this after editing prompts/commands/."
  echo "  note  Codex reads AGENTS.md at the repo root automatically."
}

install_gemini() {
  # Gemini CLI uses TOML, one file per command, with the body as `prompt`.
  echo "gemini:"
  local dest=".gemini/commands"
  mkdir -p "$dest"
  local n=0
  while read -r name; do
    {
      printf 'description = "%s"\n' "$(description_of "$SRC/$name.md" | sed 's/"/\\"/g')"
      printf 'prompt = """\n'
      # Escape backslashes for TOML, and translate the $ARGUMENTS placeholder
      # (Claude Code / Cursor / opencode / Codex) into Gemini's {{args}}.
      strip_frontmatter "$SRC/$name.md" | sed -e 's/\\/\\\\/g' -e 's/\$ARGUMENTS/{{args}}/g'
      printf '\n"""\n'
    } > "$dest/$name.toml"
    n=$((n + 1))
  done < <(commands)
  echo "  gen   $n command(s) -> $dest/*.toml"
  echo "  note  Generated from prompts/commands/. Re-run after editing them."
}

target="${1:-}"
case "$target" in
  claude)   install_claude ;;
  codex)    install_codex ;;
  cursor)   install_cursor ;;
  gemini)   install_gemini ;;
  opencode) install_opencode ;;
  all)      install_claude; install_cursor; install_opencode; install_codex; install_gemini ;;
  *)
    echo "usage: scripts/install-harness.sh claude|codex|cursor|gemini|opencode|all"
    echo
    echo "Available commands:"
    commands | sed 's/^/  /'
    exit 1
    ;;
esac

echo
echo "Done. Commands available: $(commands | tr '\n' ' ')"
