#!/usr/bin/env python3
"""Migrate user/applications.md into per-application records. One-shot.

Three subcommands, run in order, each gated on the previous:

    reconcile   compare the table against the server; report and STOP
    migrate     back up, then write user/applications/*.md and user/pipeline.md
    verify      assert every byte of every Notes cell landed in exactly one record

NOTHING IS SUMMARISED. The Notes cell becomes the record body verbatim. The
prose in those cells contains corrections, verbatim quotes and struck-through
reasoning trails; an agent rewriting them on the way through is the failure
class this repo keeps getting bitten by.

user/ is gitignored, so there is no history to fall back on. Safety is the
backup written by `migrate`, not git.
"""
import argparse
import datetime
import json
import os
import re
import shutil
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import application_record as ar  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / 'user' / 'applications.md'
RECORDS = ROOT / 'user' / 'applications'
PIPELINE = ROOT / 'user' / 'pipeline.md'
ROW = re.compile(r'^\|\s*20\d\d-\d\d-\d\d\s*\|')
SECTION = re.compile(r'^##\s+(.*)')
STATUSES = ('applied', 'phone_screen', 'onsite', 'offer', 'rejected',
            'ghosted', 'withdrawn')

# Written by build_application_index.py into the header of the file it
# generates (user/applications.md, post-migration). Its presence means the
# migration already ran and this file is now a PROJECTION, not the source
# table this script expects -- see _assert_not_generated.
GENERATED_MARKER = 'DO NOT EDIT. Generated by scripts/build_application_index.py'


def _assert_not_generated(text):
    """Refuse to treat the generated index as a source table.

    Once migrate has run once, user/applications.md is regenerated by
    build_application_index.py from user/applications/*.md and carries
    GENERATED_MARKER in its header. It still has a 'Status' column, so
    parse_table's row classifier would accept every row in it, and
    row_to_record would set every record's body to just the (nonexistent)
    'Notes' cell -- silently wiping all 28 real, hand-curated record
    bodies with no way to recover them (user/ has no git history).

    This is deliberately not gated behind --force: --force exists so a
    legitimate hand-edited SOURCE table can be re-migrated, never so the
    script's own output can be fed back into itself.
    """
    if GENERATED_MARKER in text:
        raise SystemExit(
            'user/applications.md is the GENERATED index (it carries the '
            '"DO NOT EDIT" marker written by build_application_index.py) -- '
            'the migration has already run. This script parses a '
            'hand-maintained source table; parsing its own generated output '
            'would overwrite every real record with a near-empty body. '
            'Not overridable by --force.')


def _assert_has_notes_column(text):
    """Refuse a source table whose application-row header has no 'Notes'
    column, even without GENERATED_MARKER present.

    row_to_record builds a record's entire body from row.get('Notes', '').
    A table with a 'Status' column (so parse_table accepts its rows) but no
    'Notes' column can therefore only produce empty bodies -- the same
    silent-wipe failure _assert_not_generated exists to prevent, reached by
    a different door. Checked per-header (via _scan), because the real file
    has multiple tables with different schemas and any one of them lacking
    Notes is enough to lose data if it has a Status column.
    """
    for _line, section, header, _is_row in _scan(text):
        if header is not None and 'Status' in header and 'Notes' not in header:
            raise SystemExit(
                f'table under "{section}" has a Status column but no Notes '
                'column -- refusing to migrate. Every application record\'s '
                'body comes from Notes; without it every record written '
                'would be empty. This looks like the generated index, not '
                'a hand-maintained source table.')


def _cells(line):
    # Strip the leading and trailing pipe, then split. A Notes cell may itself
    # contain "|", so split only up to the known column count and rejoin the rest.
    inner = line.strip()
    if inner.startswith('|'):
        inner = inner[1:]
    if inner.endswith('|'):
        inner = inner[:-1]
    return [c.strip() for c in inner.split('|')]


def _scan(text):
    """Walk every line once, tracking which '## ' section and which '| Date'
    header row it currently falls under. The real table is not one table: it
    is several sections, each its own header with its own column count (one
    of them has no Status column at all). Tracking state per line, once, here
    is what lets parse_table and non_row_lines agree on which table a row
    belongs to without each re-deriving it.

    Yields (line, section, header, is_row) where header is the most recent
    '| Date ...' header's cell list (or None before any header is seen), and
    is_row is True only for lines that look like a data row under a header.
    """
    section = None
    header = None
    for line in text.split('\n'):
        s = line.strip()
        m = SECTION.match(s)
        if m:
            section = m.group(1).strip()
            header = None
            yield line, section, header, False
            continue
        if s.startswith('| Date'):
            header = _cells(line)
            yield line, section, header, False
            continue
        if s.startswith('|---'):
            yield line, section, header, False
            continue
        is_row = header is not None and ROW.match(s) is not None
        yield line, section, header, is_row


def _rows_under(text, want_status):
    """Yield one dict per data row whose own table header does (want_status
    True) or does not (want_status False) contain a 'Status' column. Shared
    by parse_table and statusless_rows so a Notes cell is parsed exactly the
    same way -- same overflow handling, same rejoin spacing -- no matter
    which of the two populations it belongs to.

    Each dict carries the column keys from its own table's header, plus
    'source_table': the name of the '## ' section heading the row was found
    under, so callers can tell e.g. a 'Closed' row from a 'Live / awaiting
    response' row without re-deriving it from the columns present.
    """
    rows = []
    for line, section, header, is_row in _scan(text):
        if not is_row or ('Status' in header) != want_status:
            continue
        cells = _cells(line)
        if len(cells) > len(header):
            cells = cells[:len(header) - 1] + [' | '.join(cells[len(header) - 1:])]
        if len(cells) < len(header):
            raise SystemExit(f'row under "{section}" has {len(cells)} cells, '
                             f'header has {len(header)}:\n{line.strip()[:160]}')
        row = dict(zip(header, cells))
        row['source_table'] = section
        rows.append(row)
    return rows


def parse_table(text):
    """Return one dict per APPLICATION row -- i.e. every row under a table
    whose header has a 'Status' column. The file has three tables with three
    different schemas, not one; the last column absorbs any extra pipes.

    A table with no 'Status' column ('Started but never submitted') holds
    packets that were never actually sent; per the project's standing rule
    a form filled but not submitted is not an application, and inventing a
    status for it would violate the verbatim-or-fail migration constraint.
    Those rows are excluded here -- see statusless_rows and non_row_lines,
    which is where their Notes text goes instead.
    """
    return _rows_under(text, want_status=True)


def statusless_rows(text):
    """Return one dict per row under a table with NO 'Status' column -- the
    population parse_table excludes. These rows are not applications; their
    Notes text is moved verbatim into pipeline.md by non_row_lines, and
    missing_notes checks it landed there. Same row shape as parse_table:
    column keys from the row's own header, plus 'source_table'.
    """
    return _rows_under(text, want_status=False)


def non_row_lines(text):
    """Lines bound for user/pipeline.md: general prose, plus -- verbatim --
    every row from a table with no 'Status' column. Those rows are not
    applications (see parse_table's docstring), so they never go through
    parse_table at all; without this, they would land in neither an
    application record nor the pipeline notes, which is silent data loss.
    Table headers and separator rows are dropped either way.
    """
    out = []
    for line, section, header, is_row in _scan(text):
        s = line.strip()
        if s.startswith('| Date') or s.startswith('|---'):
            continue
        if is_row and 'Status' in header:
            continue  # application row; parse_table owns it
        out.append(line)
    return out


def _server_apps():
    base = os.environ.get('JOBHUB_URL', 'http://localhost:8080')
    req = urllib.request.Request(
        f'{base}/api/applications?limit=500',
        headers={'Authorization': f'Bearer {os.environ.get("JOBHUB_API_TOKEN", "")}'})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    return data if isinstance(data, list) else data.get('applications', [])


def cmd_reconcile(args):
    text = TABLE.read_text()
    _assert_not_generated(text)
    rows = parse_table(text)
    print(f'table:  {len(rows)} rows')
    print(f'prose:  {len(non_row_lines(text))} non-row lines -> user/pipeline.md')

    try:
        apps = _server_apps()
    except Exception as e:  # noqa: BLE001 - reporting beats crashing here
        print(f'\nCOULD NOT REACH THE SERVER: {e}', file=sys.stderr)
        print('Reconcile needs both sides. Fix the connection and re-run.',
              file=sys.stderr)
        return 1
    print(f'server: {len(apps)} records\n')

    tkeys = {(r['Company'].strip().lower()) for r in rows}
    skeys = {(a.get('company') or '').strip().lower() for a in apps}

    only_table = sorted(tkeys - skeys)
    only_server = sorted(skeys - tkeys)
    for label, items in (('in the table but NOT on the server', only_table),
                         ('on the server but NOT in the table', only_server)):
        print(f'{len(items)} {label}')
        for c in items:
            print(f'  - {c}')

    if only_table or only_server:
        print('\nSTOPPING. Resolve these before running `migrate`: decide for each '
              'whether it is a real application, and if so which side is right.',
              file=sys.stderr)
        return 1
    print('\nBoth sides agree. Safe to run `migrate`.')
    return 0


def slug(company, role):
    """Lowercase, hyphenated, matching the user/tailored/ packet segments."""
    def part(s):
        s = re.sub(r'[^a-z0-9]+', '-', s.lower())
        return s.strip('-')
    return f'{part(company)}-{part(role)}'


def row_to_record(row):
    """Map one table row onto a record dict. Verbatim body; no summarising.

    row comes from parse_table, so it always has a 'Status' column -- rows
    from the Status-less table never reach here (see parse_table's
    docstring). The 'Closed' table has no 'Resume' column at all; resume is
    optional in the record format, so it is simply omitted rather than
    invented.
    """
    status = re.sub(r'[*`]', '', row.get('Status', '')).strip().lower()
    status = status.split()[0] if status else ''
    if status not in STATUSES:
        raise SystemExit(
            f'row for {row.get("Company")!r} has status {row.get("Status")!r}, '
            f'which is not one of {", ".join(STATUSES)}. Map it by hand and re-run.')
    rec = {
        'company': row['Company'],
        'role': row['Role'],
        'status': status,
        'source': row.get('Source', 'unknown'),
        # The table has no submitted column. A portal row was sent; a recruiter
        # row may not have been. Default from Source, and expect Andre to
        # correct the recruiter rows -- this is recorded in the migration report.
        'submitted': 'recruiter' not in row.get('Source', '').lower(),
        'applied': row['Date'],
        'body': row.get('Notes', '').strip() + '\n',
    }
    if row.get('Resume'):
        rec['resume'] = row['Resume']
    return rec


def _backup_path(stamp):
    """A backup directory for today that is guaranteed not to already hold
    an applications.md backup. Both applications.md and (if present)
    pipeline.md get copied into whatever directory this returns.

    The target is 'user/_backup-<date>/'. If 'applications.md' is already
    there -- e.g. a first run today wrote it, then row_to_record raised on
    a bad status and the operator hand-edited applications.md and re-ran --
    we must NOT overwrite it: it may be the only copy of the pre-edit
    original, and user/ has no git history. Instead, number the directory:
    '_backup-<date>-2', '_backup-<date>-3', ...
    """
    backup = ROOT / 'user' / f'_backup-{stamp}'
    n = 1
    while (backup / 'applications.md').exists():
        n += 1
        backup = ROOT / 'user' / f'_backup-{stamp}-{n}'
    return backup


def cmd_migrate(args):
    text = TABLE.read_text()
    # Both checks run unconditionally, before --force is even consulted:
    # neither is a "would overwrite existing output" concern that --force
    # is meant to override -- both mean the input itself cannot be
    # migrated safely.
    _assert_not_generated(text)
    _assert_has_notes_column(text)

    blockers = []
    if RECORDS.exists() and any(RECORDS.glob('*.md')):
        blockers.append(f'{RECORDS} already has records')
    if PIPELINE.exists():
        blockers.append(f'{PIPELINE} already exists')
    if blockers and not args.force:
        print('; '.join(blockers) + '. Re-run with --force to overwrite.',
              file=sys.stderr)
        return 1

    stamp = datetime.date.today().isoformat()
    backup = _backup_path(stamp)
    backup.mkdir(parents=True, exist_ok=True)
    shutil.copy2(TABLE, backup / 'applications.md')
    print(f'backed up applications.md -> {backup.relative_to(ROOT)}/')

    # pipeline.md gets the same protection as applications.md: a --force
    # rerun is about to overwrite it below, and any hand-curation added
    # since the last migration only survives if it is backed up first.
    if PIPELINE.exists():
        shutil.copy2(PIPELINE, backup / 'pipeline.md')
        print(f'backed up pipeline.md -> {backup.relative_to(ROOT)}/')

    # RECORDS holds the live, hand-curated record files -- the write loop
    # below overwrites any of them whose slug matches a row in this run,
    # by design, on a --force rerun. Without this, a --force invocation
    # against real records (the exact workflow this script documents:
    # hit an unmappable status, hand-edit applications.md, re-run) wipes
    # them with nothing to recover from, since user/ has no git history.
    # Same collision-free _backup_path directory as applications.md and
    # pipeline.md above, so no earlier backup is ever clobbered.
    if RECORDS.exists() and any(RECORDS.iterdir()):
        shutil.copytree(RECORDS, backup / 'applications')
        print(f'backed up user/applications/ -> '
              f'{backup.relative_to(ROOT)}/applications/')

    rows = parse_table(text)
    RECORDS.mkdir(parents=True, exist_ok=True)

    # Detect slug collisions before writing anything, so a clash never
    # silently clobbers an already-written record. slug() normalises away
    # punctuation, so two distinct rows ("Backend/Platform Engineer" vs.
    # "Backend-Platform Engineer") can land on the same name.
    by_slug = {}
    for row in rows:
        name = slug(row['Company'], row['Role'])
        by_slug.setdefault(name, []).append(row)
    collisions = {name: rs for name, rs in by_slug.items() if len(rs) > 1}
    if collisions:
        print('SLUG COLLISION -- stopping without writing any records:', file=sys.stderr)
        for name, rs in collisions.items():
            print(f'  {name}:', file=sys.stderr)
            for r in rs:
                print(f'    - {r["Company"]!r} / {r["Role"]!r}', file=sys.stderr)
        print('Rename one of the roles (or disambiguate by hand) and re-run.',
              file=sys.stderr)
        return 1

    written, guessed = [], []
    for row in rows:
        rec = row_to_record(row)
        name = slug(rec['company'], rec['role'])
        (RECORDS / f'{name}.md').write_text(ar.serialise(rec))
        written.append(name)
        if 'recruiter' in rec['source'].lower():
            guessed.append(name)

    PIPELINE.write_text(
        '# Pipeline\n\n'
        '<!-- Cross-application strategy, moved verbatim from applications.md\n'
        f'     on {stamp} by migrate_applications.py. This file is regenerated\n'
        '     by that script on a --force re-run -- hand edits made after\n'
        '     migration are backed up alongside applications.md before being\n'
        '     overwritten, so they are preserved, not lost. -->\n\n'
        + '\n'.join(non_row_lines(text)).strip() + '\n')

    print(f'wrote {len(written)} records -> user/applications/')
    print(f'wrote user/pipeline.md')
    if guessed:
        print('\nCHECK BY HAND -- `submitted` was inferred from Source for these '
              'recruiter rows and may be wrong:')
        for n in guessed:
            print(f'  - user/applications/{n}.md')
    return 0


def missing_notes(table_text, records_dir, pipeline_text=None):
    """Return every Notes cell whose text was not preserved in its expected
    destination. The source table has TWO populations, and both must be
    checked or a bad migration can drop one of them and still report clean:

    1. Rows from a table WITH a 'Status' column (parse_table) became
       application records. Each such row is checked against its OWN
       record file specifically -- records_dir / (slug(company, role) +
       '.md') -- not against the concatenation of every record body. If
       that file does not exist, the row is reported missing on that basis
       alone (a dropped record is caught by absence, before any text
       search runs). If it exists, the row's Notes cell must be contained
       in THAT record's body. Checking a per-row target this way, instead
       of a global blob, is required: an early version of this function
       joined every record body into one string and asked whether each
       Notes cell appeared anywhere in it. That let a FULLY DROPPED record
       hide and report clean whenever its Notes text happened to be a
       substring of some other, unrelated record's body -- plausible
       precisely because Notes cells are often short and generic ("Short
       note.", "Following up."). A record that was never written must be
       caught by its own absence, never by a coincidental textual match
       elsewhere.
    2. Rows from a table WITHOUT a 'Status' column (statusless_rows --
       'Started but never submitted' in the real file) are not applications;
       their Notes text was moved verbatim into pipeline.md instead, via
       non_row_lines. Pass pipeline_text (pipeline.md's contents) to check
       this population too. Omit it only when you deliberately want
       population 1 checked in isolation -- the check is opt-in, not
       silently skipped: cmd_verify always passes it.

       There is no per-row target file for this population -- all of it
       lands in the single pipeline.md -- so this half of the check is
       still a blob-containment check against pipeline_text, and the same
       hole described above is NOT closed here: a status-less row that was
       dropped entirely could still hide behind another line's text
       already present in pipeline.md, especially for a short, generic
       note. This is a real, currently-open gap in what this function
       guarantees for population 2, not just a theoretical one.

    Every cell value compared here was produced by parse_table/statusless_rows
    (both built on _rows_under/_cells) -- the SAME parser that produced the
    record bodies and pipeline.md in the first place. That matters because
    _cells rejoins an embedded '|' inside a Notes cell with a single
    ' | ', which can differ from the source's original spacing around that
    pipe. Comparing against a value pulled from that same parse (rather than
    a raw substring of the backup text) means that rejoin-spacing is applied
    identically on both sides of the comparison, so it cannot itself cause a
    false failure -- no loosening of the containment check was needed to
    handle it. The trade-off: this check only proves the migration did not
    DROP anything the parser produced. A bug inside _cells/_rows_under
    itself -- one that scrambles an embedded-pipe cell during parsing --
    would be invisible here, because row_to_record and this function would
    derive the identical wrong value from the identical buggy parse. No row
    in the live file currently contains an embedded pipe, so this path is
    latent, not active.

    Containment, not equality: a record body may gain frontmatter and
    whitespace, but it must not LOSE prose. This is the only check standing
    between a bad migration and unrecoverable data, because user/ is not in
    git.
    """
    records_dir = Path(records_dir)
    missing = []
    for row in parse_table(table_text):
        cell = row.get('Notes', '').strip()
        if not cell:
            continue
        record_path = records_dir / (slug(row.get('Company', ''),
                                          row.get('Role', '')) + '.md')
        if not record_path.exists():
            missing.append(cell)
            continue
        body = ar.load(record_path)['body']
        if cell not in body:
            missing.append(cell)
    if pipeline_text is not None:
        for row in statusless_rows(table_text):
            cell = row.get('Notes', '').strip()
            if cell and cell not in pipeline_text:
                missing.append(cell)
    return missing


def cmd_verify(args):
    stamp = args.backup or datetime.date.today().isoformat()
    backup = ROOT / 'user' / f'_backup-{stamp}' / 'applications.md'
    if not backup.exists():
        print(f'no backup at {backup}. Pass --backup <YYYY-MM-DD>.', file=sys.stderr)
        return 1

    text = backup.read_text()
    pipeline = PIPELINE.read_text() if PIPELINE.exists() else ''
    missing = missing_notes(text, RECORDS, pipeline)
    prose = '\n'.join(non_row_lines(text)).strip()
    lost_prose = [l for l in prose.split('\n') if l.strip() and l not in pipeline]

    if missing:
        print(f'{len(missing)} Notes cell(s) did NOT land in any record or in '
              'pipeline.md:', file=sys.stderr)
        for m in missing:
            print(f'  - {m[:120]}...', file=sys.stderr)
    if lost_prose:
        print(f'{len(lost_prose)} non-row line(s) missing from pipeline.md:',
              file=sys.stderr)
        for l in lost_prose[:10]:
            print(f'  - {l[:120]}', file=sys.stderr)

    if missing or lost_prose:
        print('\nDO NOT replace applications.md. The backup is intact at '
              f'{backup.parent.relative_to(ROOT)}/.', file=sys.stderr)
        return 1
    print('every Notes cell and every non-row line is accounted for')
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    sub.add_parser('reconcile', help='compare table and server; report and stop')
    m = sub.add_parser('migrate', help='back up, then write records and pipeline.md')
    m.add_argument('--force', action='store_true',
                   help='overwrite an existing user/applications/')
    v = sub.add_parser('verify', help='assert nothing was lost in the migration')
    v.add_argument('--backup', help='backup date, YYYY-MM-DD (default: today)')
    a = ap.parse_args()
    return {'reconcile': cmd_reconcile, 'migrate': cmd_migrate,
            'verify': cmd_verify}[a.cmd](a)


if __name__ == '__main__':
    sys.exit(main())
