#!/usr/bin/env python3
"""Turn an Ollama /api/tags response on stdin into an opencode provider block.

Called by `scripts/install-harness.sh opencode`. Not useful on its own.

    curl -s $OLLAMA_HOST/api/tags | OLLAMA_BASE=... python3 opencode_ollama_config.py

Two things here are less obvious than they look:

**The context limit is the server's, not the model's.** /api/tags reports what a
model was trained to handle -- 262144 for the qwen3 family. Ollama serves it at
the host's num_ctx, which is 32768 by default. opencode believes the number it
is given and will happily pack 200k tokens into a request the server then
truncates from the middle, with nothing in either log saying so. So the
advertised ceiling is min(model, server).

**Only tool-capable models are listed.** opencode drives every command through
read/edit/bash tools. A model without the `tools` capability (gemma3, opencoder)
connects, answers in prose, and never reads a file -- which looks like a bad
model rather than a misconfiguration.
"""
import json
import os
import sys

MAX_CTX = int(os.environ.get('OLLAMA_MAX_CTX') or 32768)
BASE = (os.environ.get('OLLAMA_BASE') or 'http://localhost:11434').rstrip('/')
MARKER = os.environ.get('OLLAMA_MARKER') or 'generated by scripts/install-harness.sh'


def main():
    tags = json.load(sys.stdin).get('models', [])

    # Several tags are the same weights under different names (qwen3:30b and
    # qwen3:30b-a3b share a digest). Listing both doubles the model picker for
    # no choice, so the shortest name wins and the rest are dropped.
    by_digest = {}
    for m in tags:
        caps = m.get('capabilities') or []
        if 'tools' not in caps or 'embedding' in caps:
            continue
        d = m.get('digest') or m.get('name')
        if d not in by_digest or len(m['name']) < len(by_digest[d]['name']):
            by_digest[d] = m

    models = {}
    for m in sorted(by_digest.values(), key=lambda m: m['name']):
        det = m.get('details') or {}
        ctx = min(int(det.get('context_length') or MAX_CTX), MAX_CTX)
        size = det.get('parameter_size') or '?'
        models[m['name']] = {
            'name': f"{m['name']} ({size})",
            'tool_call': True,
            'limit': {'context': ctx, 'output': min(ctx // 4, 8192)},
        }

    if not models:
        print('no tool-capable models on this Ollama host', file=sys.stderr)
        return 1

    json.dump({
        '$schema': 'https://opencode.ai/config.json',
        'provider': {
            'ollama': {
                'npm': '@ai-sdk/openai-compatible',
                'name': f'Ollama local ({MARKER})',
                'options': {'baseURL': f'{BASE}/v1'},
                'models': models,
            },
        },
    }, sys.stdout, indent=2)
    sys.stdout.write('\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
